### ISSUE TITLE
Broken textures and planets

### ISSUE THREAD

**Issue by PlaneteniumTheory** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#1]
So i installed this mod and followed the instructions of this video https://youtu.be/wdbEZ-bzWyo ,and when i started the game everything was looking good and working fine but my fps was really low so i decided to turn some of the planets from true to false.I opened the game and everything was broken including kerbin.I have a few screenshots of the csg files and the broken textures and my gamedata.
![Screenshot (1298)](https://user-images.githubusercontent.com/76861138/103451752-cae69000-4ced-11eb-8b02-d8b1cd348aea.png)
![20210101184759_1](https://user-images.githubusercontent.com/76861138/103451773-eea9d600-4ced-11eb-85ac-4a303a64676b.jpg)
![20210101184810_1](https://user-images.githubusercontent.com/76861138/103451774-f0739980-4ced-11eb-8c14-1ec91ae4f09f.jpg)
![20210101184753_1](https://user-images.githubusercontent.com/76861138/103451776-f1a4c680-4ced-11eb-8c99-057884498c46.jpg)

![Screenshot (1299)](https://user-images.githubusercontent.com/76861138/103451756-cc17bd00-4ced-11eb-9b64-c7eceb99b616.png)
![Screenshot (1300)](https://user-images.githubusercontent.com/76861138/103451757-ccb05380-4ced-11eb-9411-2080190eb6b1.png)
![Screenshot (1301)](https://user-images.githubusercontent.com/76861138/103451759-cd48ea00-4ced-11eb-84c4-a03e4e3d60dd.png)
![Screenshot (1302)](https://user-images.githubusercontent.com/76861138/103451760-cde18080-4ced-11eb-9f3d-6b7fccf8ff32.png)
![Screenshot (1297)](https://user-images.githubusercontent.com/76861138/103451761-ce7a1700-4ced-11eb-9420-f76558c20964.png)

 folder.

**Comment by StarCrusher96** [comment]
Hi 
GU is not compatible with AVP. When you install AVP with GU, you need to compress the Stock Clouds. Or remove AVP entirely so GU Visuals can take over.

![unknown](https://user-images.githubusercontent.com/17100011/103455155-c8366b80-4cea-11eb-8f6c-bb4caff4357a.png)

**Comment by PlaneteniumTheory** [comment]
Can you specify which folders as I am having trouble finding the right ones. Could you send screenshots based on these settings?
![Screenshot (1303)](https://user-images.githubusercontent.com/76861138/103478501-34999380-4ded-11eb-8dc3-de48f9f33d93.png)
![Screenshot (1304)](https://user-images.githubusercontent.com/76861138/103478502-36635700-4ded-11eb-8e69-a7d92b742164.png)

**Comment by PlaneteniumTheory** [comment]
Hello,
The issue was caused by EVE,I have now fixed it.
