### ISSUE TITLE
Carreer mode: missions to GU systems offered too early in the game

### ISSUE THREAD

**Issue by RenatoUtsch** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#12]
Hi, thank you for all your work on this amazing mod.

I am playing GU on carreer mode and I've just finished the normal set of Minmus missions from stock KSP. Normally what would come afterwards is missions suggesting to explore the solar system and planets like Eve or Duna. However, instead of these missions the next "official" mission I was offered is to visit Kespilon Kirilani (sorry for the extremely poor quality photo - I should have taken a screenshot instead):

![photo1645289781](https://user-images.githubusercontent.com/836333/154849419-f17d45a7-7ddf-459e-8cc5-296230629ec8.jpeg)

This mission not only seems to provide a very low reward (after all, it *is* an interstellar mission!) but I don't have any technologies at this point in the game that would allow me to complete this mission.

Not only that, after it expires the same mission is offered again and again, and I am not getting any other missions, for example, to explore Duna or Eve.

Am I doing something wrong in carreer mode to have been offered this mission? How can I edit which missions are offered at each point in time? If you can provide details (or links to tutorials) about where to edit this in the config files I can try to balance the mission offering so that these missions would start to be offered _after_ I've explored the solar system.

**Comment by StarCrusher96** [comment]
KSP was never made for interstellar gameplay. The only fix for this is to ask SQUAD to remake the game.

**Comment by RenatoUtsch** [comment]
I guess that will be KSP 2 then :)

Where are these missions defined? Did you have to implement these missions somewhere in the mod files, or are they auto generated by KSP?

**Comment by StarCrusher96** [comment]
Generated by ksp :)

**Comment by RenatoUtsch** [comment]
Ah ok, so then there's no way to fix this. Thanks a lot for taking the time to explain!

**Comment by RenatoUtsch** [comment]
Guess I'll move to science mode now.
