### ISSUE TITLE
Even if I follow all installation steps, the systems aren't appearing on the tracking station

### ISSUE THREAD

**Issue by BiggerBen13** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#13]

**Comment by StarCrusher96** [comment]
Need more info, logs, ...

**Comment by BiggerBen13** [comment]
so basically i followed the instructions of ballisticfoxes install tutorial, and the game boots up normally, but when I create a new save file and open the tracking station, I cant zoom past the Kerbol system.

I am just running eve, Kopernicus(current version) and scatterer
I appended a log file
[KSP.log](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/files/8119366/KSP.log)

**Comment by StarCrusher96** [comment]
I mentioned that installation guide is dated. 
You just need to merge 'gu' folders in GameData. That's all.

**Comment by BiggerBen13** [comment]
thanks, you should probably remove the video from the readme then
I will try again

**Comment by BiggerBen13** [comment]
Nothinh changed, I removed alien worlds and installed alpha centaury, but there still are no systems, I also just merged the GU files
[KSP.log](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/files/8119706/KSP.log)

I appended a new log

![Capture1](https://user-images.githubusercontent.com/60266903/155208056-0b9701dc-4742-46ec-9607-d4db010b561a.PNG)

![Capture](https://user-images.githubusercontent.com/60266903/155208070-0d3b84a2-ab0e-4146-98ad-e3a25b64eec2.PNG)

a screenshot of my gamedata folder and one of the gu folder

**Comment by BiggerBen13** [comment]
this looks like an error to me
[LOG 19:46:28.755] [EVE CloudsManager]: Unable to parse config node:
OBJECT
{
	name = Iores-Aurora1
	body = Iores
	speed = 0,70,0
	detailSpeed = 1000,3000,0
	altitude = 25000
	offset = 0.25,0,0
	settings
	{
		_DetailScale = 6
		_UVNoiseScale = 0.5
		_UVNoiseStrength = 0.05
		_UVNoiseAnimation = 0.05,0.02
		_DetailDist = 1E-07
		_Color = 255,255,555,175
		_MainTex
		{
			value = GU/EVE/Textures/Aurora2
		}
		_DetailTex
		{
			value = GU/EVE/Textures/detailaurora
		}
		_UVNoiseTex
		{
			value = GU/EVE/Textures/uvnoise1
		}
	}
	layer2D
	{
		macroCloudMaterial
		{
			_MinLight = 0.75
		}
	}
}

[LOG 19:46:28.755] EVEManager: Issue loading CloudsManager! Error:
UnityEngine.UnityException: Unable to apply node! ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Atmosphere.CloudsManager.ApplyConfigNode (ConfigNode node) [0x00026] in <344479ccb68743409608815de7dc27b3>:0 
  at EVEManager.EVEManagerBase.Apply () [0x00032] in <f154ec1977ba466791837ecfba96a814>:0 
   --- End of inner exception stack trace ---
  at EVEManager.EVEManagerBase.Apply () [0x0005f] in <f154ec1977ba466791837ecfba96a814>:0 
  at EVEManager.EVEManagerBase.LoadConfig () [0x00062] in <f154ec1977ba466791837ecfba96a814>:0 
  at EVEManager.GenericEVEManager`1[T].Setup () [0x00016] in <f154ec1977ba466791837ecfba96a814>:0 
  at EVEManager.GlobalEVEManager.Setup (System.Boolean late) [0x0005c] in <f154ec1977ba466791837ecfba96a814>:0

**Comment by StarCrusher96** [comment]
Yeah like I said, something's up with Alien Worlds. 
Can you show me the _Systems folder?

**Comment by BiggerBen13** [comment]
![Capture2](https://user-images.githubusercontent.com/60266903/155209305-53786b51-7f4b-42d4-bf38-b0678680358c.PNG)

**Comment by BiggerBen13** [comment]
I removed alien worlds after you said that

**Comment by StarCrusher96** [comment]
and it does or does not load?

**Comment by BiggerBen13** [comment]
the game loads
but no systems

**Comment by StarCrusher96** [comment]
it should, is it possible to join the discord?

**Comment by BiggerBen13** [comment]
just did
