### ISSUE TITLE
The atmosphere and clouds of some planets in ALPHA CENTAURI doesn't seem to be normal.

### ISSUE THREAD

**Issue by zrh114311** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#14]
Clouds are strangely stretched in these places.I use the latest version of GU,EVE and Scatter.Is there any solution?
![Kerbal Space Program Screenshot 2022 03 01 - 13 31 22 34_LI](https://user-images.githubusercontent.com/51064462/156115742-df30edd1-8379-4f0e-8cf6-65be2a055c8b.jpg)

![Kerbal Space Program Screenshot 2022 03 01 - 13 30 40 59_LI](https://user-images.githubusercontent.com/51064462/156115699-773661b1-9625-4870-a333-1c9e6fa29dcd.jpg)

**Comment by StarCrusher96** [comment]
Hi 
That's an EVE issue. 
I'm affraid i cannot fix this. You'll need to contact the dev of EVE :)

**Comment by ballisticfox** [comment]
This is due to the way EVE calculates cloud shadows.
If you look closely you can see the shadows are actually being cast from the direction of the sun.
