### ISSUE TITLE
Add CKAN support 

### ISSUE THREAD

**Issue by glowingc4** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#15]
I can't really install this normally with TONNNS of mods. (around 100 to be exact, and my 5/6 year old laptop can work just fine)
Please add CKAN support, and installing it normally takes a few hours, (last time i installed it it crashed my game because of too many mods)

**Comment by StarCrusher96** [comment]
I'm sorry but you only need a few mods to get GU running.  So I think you're making mistakes or not following the guide. In that case I'll need logs of a clean GU install to verify the issue related to GU. 

CKAN support will not happen. Sorry.

**Comment by ohthebiomesyoullgoooooooo** [comment]
Okay, that's fine, I'll remove my installed mods later and install GU first. Then I will put all my mods back, (i will NOT install interstellar, since with so many mods and GU's loading time, i cannot install interstellar

**Comment by glowingc4** [comment]
ARE YOU FUCKING SERIOUS YOU ADDED CKAN SUPPORT AD- are YOU f-
