### ISSUE TITLE
Scatterer atmosphere not loading with MM 4.1.4

### ISSUE THREAD

**Issue by Faryzal2020** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#2]
Note: all installations are according to the "How to install Galaxies Unbound: A Stellar Odyssey" guide in the KSP forum, with GU config on default.

Test 1 (GU + MM):
Mods: 

- Kopernicus release 80
- GU 1.0.2-3 (with GE_Visuals_EVE and GE_Visuals_Scatterer)
- EVE Redux 1.11.2.1 (With config 1.2.2.1)
- Scatterer 0.0723 (With stock config from CKAN)
- Module Manager 4.1.4

Result:

- Clouds are properly loaded
- no scatterer atmosphere to be seen
- Went to tracking station then zoom out, there are no other star systems and planets outside of kerbol system

Test 2 (without MM):
Mods: 

- Kopernicus release 80
- GU 1.0.2-3 (with GE_Visuals_EVE and GE_Visuals_Scatterer)
- EVE Redux 1.11.2.1 (With config 1.2.2.1)
- Scatterer 0.0723 (With stock config from CKAN)

Result:

- Clouds are properly loaded
- Scatterer atmosphere loaded
- In the tracking station, able to zoom further from kerbol system and there are other starsystems outside of kerbol.

Test 3 (without GU):
Mods: 

- Kopernicus release 80
- EVE Redux 1.11.2.1 (With config 1.2.2.1)
- Scatterer 0.0723 (With stock config from CKAN)
- Module Manager 4.1.4
Result:

- Clouds are properly loaded
- Scatterer atmosphere loaded

I need all the GU, scatterer, and MM to work together so that i can add other mods. is this the right place to ask?

**Comment by StarCrusher96** [comment]
Hi, everything should work. 
Are you able to send a screen of your gamedata folder - gu folder or share logs?

**Comment by Faryzal2020** [comment]
Gamedata:
![image](https://user-images.githubusercontent.com/8612170/110206328-9048d180-7eaf-11eb-84f9-39a0e99c4509.png)

GU folder:
![image](https://user-images.githubusercontent.com/8612170/110206339-9d65c080-7eaf-11eb-8338-a73d6bfc5bbf.png)

KSP log:
[KSP.log](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/files/6095271/KSP.log)

**Comment by Faryzal2020** [comment]
thank you! it works now, comparing with your gamedata folder made me realized that i dont have ModularFlightIntegrator for kopernicus, i think i accidentally deleted that. I reinstalled that and now everything works perfectly.
