### ISSUE TITLE
RSS compatible?

### ISSUE THREAD

**Issue by ignaciourteaga** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#20]
Hi!

I am using 1.12.3, and the latest version of Kopernicus installed from CKAN.

I tried to install Galaxy Unbound after Kopernicus and it works ok with the Kerbal System. 

When I install RSS it fails to load.

Also I tried to install RSS first and then Galaxy Unbound and can not see the rest of the stars. (Only Sol)

Is suposed Galaxy Unbound to work with Real Solar System?

Thank you very much!

Ignacio

**Comment by StarCrusher96** [comment]
Hi, next update should allow RSS compatibility.
