### ISSUE TITLE
GU's Scatterer patch creates duplicate copies of values

### ISSUE THREAD

**Issue by JonnyOThan** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#21]
All of the lines in GU/Scatterer/_config.cfg should have `%` in front of them for edit-or-create.  As it is now, they add a second copy of the field to the Scatterer_config node.  Depending on how scatterer reads these values, they might be completely ignored.

**Comment by StarCrusher96** [comment]
hi, can you specify to which configs these apply?

**Comment by StarCrusher96** [comment]
Edited for the next release :) thanks!
