### ISSUE TITLE
Issue with Galaxy mode after leaving the Tracking Station of the base

### ISSUE THREAD

**Issue by VirtualGaming1** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#22]
so when I first load the save with Galaxy Mode enabled, it look fine beside the blueish lighting like it say in the installion and config.

but when I enter tracking station and then leave I get this

![image](https://user-images.githubusercontent.com/20447403/199162676-6b68a347-e258-4b50-a639-3a6f58020c0c.png)

Work around fix: The way to fix that during gameplay is to reload the save.

**Comment by StarCrusher96** [comment]
Kopernicus bug and normal. Cannot be fixed and doesn't interfere with gameplay. 
Buttons on the left still work as well :)

**Comment by VirtualGaming1** [comment]
> Kopernicus bug and normal. Cannot be fixed and doesn't interfere with gameplay. Buttons on the left still work as well :)

Sound good and I kinda forgot about those buttons <.< >.>
but it dose drive me nuts.

I do think it would help to keep this open as it is an active issue and will help to find this more if anyone else thinking of making an issue that is the exact same as this

**Comment by KatharineRosewood** [comment]
@StarCrusher96 I have the same issue or very similar. Is it something that cannot ever be fixed or is it something that Kopernicus needs a fix for?
