### ISSUE TITLE
Loading Failure with Parallax 2.0.1 (compatibility issue)

### ISSUE THREAD

**Issue by natalie-cs** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#23]
"Kopernicus could not load the planet pack because of an exception while loading." I have tried uninstalling different mods and seeing results, It works fine without parallax and the game works fine with parallax but without GU

Files:
[KSP.log](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/files/10188712/KSP.log)
[ModuleManager.zip](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/files/10188718/ModuleManager.zip)

Kopernicus Log (Parallax issue here)
[Kopernicus.log](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/files/10188727/Kopernicus.log)

mod list is in ksp.log

**Comment by StarCrusher96** [comment]
![image](https://user-images.githubusercontent.com/17100011/206557629-f9baa732-b548-4e38-861a-0211f93ccc39.png)

**Comment by natalie-cs** [comment]
ohhhhhhh, i saw this before and knew it, but i read it again and thought it said it was now working on 2.0, sry about that lol
