### ISSUE TITLE
Leethe being selected after Sun in Exploration Contracts

### ISSUE THREAD

**Issue by MrOverlord45** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#4]
![image](https://user-images.githubusercontent.com/83890818/124640111-f42dd780-de5a-11eb-9ec1-bbe895ca0d74.png)

So, the name issue displayed has been plaguing me since I installed the mod, not sure why it's doing that and if it can be fixed but I thought I'd report it just in case, but what caught my attention this time was the contract.
See, the contract appeared after I completed the "Have 2 vessels dock in orbit of the Mun" Explore Contract. I have no idea if that's intentional, but it really doesn't feel like it is. If it is... god damn it. If it isn't, well that's why I put this here, so it can be fixed.

Edit: I am now utterly convinced it's a bug, after seeing the length of time it'd take to get a probe at my stage of the campaign over to Lich, which is thousands of years.

**Comment by StarCrusher96** [comment]
Oh i'm sorry that's a loc mistake I overlooked, i'll be uploading a new Lich system with a fix in a few minutes! 
Sadly the contract thing is not something we can fix. KSP 1 was never made for interstellar travel. Mods like contractconfigurator can overcome this. But we cannot fix how the game picks contracts. It tends to go for bodies beyond Eeloo.

**Comment by MrOverlord45** [comment]
Appreciate the response and glad I could help. I have used the Configurator but never that deep, so I'll see if I can figure that out. Hopefully it won't be too difficult to figure out, and even if it is, it'll be on the internet somewhere. Thanks for the help.

**Comment by MrOverlord45** [comment]
Ok, so I reopened this for the reason that I can't figure out why Contract Configurator is still selecting Leethe, even with the Exploration Plus contract pack. I know it has something to do with the next unvisited body, but I can't figure out where the Configurator selects that. Any ideas?

**Comment by StarCrusher96** [comment]
I'm sorry :s I myself don't use it or got time to figure it out. Might be interesting to ask around on the forums or gu discord.

**Comment by MrOverlord45** [comment]
Might just do my own thing, I'll close this up again since there seems to be no clean fix for it.
