### ISSUE TITLE
Oceans don't render with Scatterer installed, atmospheres have no clouds

### ISSUE THREAD

**Issue by BillKerm** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#5]
KSP.log: https://www.mediafire.com/file/1jxsnnl8pq6m5er/KSP.log/file

Tested with KSP 1.12.2 and 1.11.2, using the most up-to-date release of GU, with the recommended version of Scatterer, as well as the current version of Scatterer.
Same result on all four tests V V V

![image](https://user-images.githubusercontent.com/87102207/125178518-a686d700-e19a-11eb-9d65-c5853a5080b8.png)
KSC ^ ^
![image](https://user-images.githubusercontent.com/87102207/125178964-8e18bb80-e19e-11eb-839b-3d238174dd66.png)
Isus's oceans ^ ^
![image](https://user-images.githubusercontent.com/87102207/125178975-be605a00-e19e-11eb-9b2e-edad54959c06.png)
Same spot as above, but from higher up ^ ^ (note: you can see the ocean from here, but then it transitions to being invisible as I move the camera closer)

Oceans don't render whatsoever. EVE also adds no clouds, and Scatterer's atmospherics don't work properly.
Once I remove Scatterer, the oceans return to normal. Once I remove GU, EVE and Scatterer return to normal.

I have no clue as to what's happening. I suspect that the EVE and Scatterer configs might have some issues, but that's honestly a shot in the dark.

**Comment by StarCrusher96** [comment]
I'll need more info about your set up, logs and screens of GU folder and GameData.
The configs work, there's no question about that. The issue is probably an installation or set up problem. 

Get back to me with the stuff i need, and i'll look into it.
