### ISSUE TITLE
Please make a merged zip with all files available 

### ISSUE THREAD

**Issue by dafrandle** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#8]
For individuals who cant download these files in 2 seconds we might want to go do other things (away from our computer) while they download. This is not possible with they system as (at least with my internet) trying to make more than 3 concurrent downloads cause them all to fail - even if I pause all but one.

I wager 99% of people who come here at least want **all** of these:
 System_AlphaCentauri.zip373 MB
 System_EpsilonEridani.zip382 MB
 System_Lich.zip94.7 MB
 System_Luhman16.zip161 MB
 System_Sirius.zip215 MB
 System_TauCeti.zip241 MB
 System_Trappist-1.zip

 so if you wont pack every and all files - at least pack these together for us
 
 please

**Comment by StarCrusher96** [comment]
This set up was chosen because it allows GU to be modular.

**Comment by dafrandle** [comment]
i'm not saying dont provided them individually

just **additionally** include a file with all of them together
