### ISSUE TITLE
Errors on Rescale_Sigma

### ISSUE THREAD

**Issue by RenatoUtsch** [StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey#9]
I updated my version of Galaxies Unbound from 1.1 to 1.2 and these errors started appearing on ModuleManager. Here is the relevant output from KSP.log:

```
[ERR 20:12:24.164] Error - node name does not have balanced brackets (or a space - if so replace with ?):
GU/Configs/GU_Patches/Rescale_Sigma/10x/@Kopernicus:HAS[@GU_GENERAL_Settings]:HAS[#Scale[10]]]:BEFORE[SigDim]
[ERR 20:12:24.164] Error - node name does not have balanced brackets (or a space - if so replace with ?):
GU/Configs/GU_Patches/Rescale_Sigma/2.5x/@Kopernicus:HAS[@GU_GENERAL_Settings]:HAS[#Scale[2.5]]]:BEFORE[SigDim]
[WRN 20:12:24.164] unrecognized trailer: ',*' on: GU/Configs/GU_Patches/Rescale_Sigma/2.5x/@EVE_CLOUDS[*]:LAST[GU]:HAS[@GU_GENERAL_Settings:HAS[#Scale[2.5]]],*
...
[WRN 20:12:41.022] 1 warning related to GameData/GU/Configs/GU_Patches/Rescale_Sigma/2.5x.cfg
[WRN 20:12:41.022] Errors in patch prevents the creation of the cache
[LOG 20:12:41.136] ModuleManager: 6546 patches applied, found <color=yellow>1 warning</color>, found <color=orange>2 errors</color>
1 error related to GameData/GU/Configs/GU_Patches/Rescale_Sigma/10x.cfg
1 error related to GameData/GU/Configs/GU_Patches/Rescale_Sigma/2.5x.cfg
```

**Comment by RenatoUtsch** [comment]
I'm not sure if it is relevant, but I'm using TweakScale - Rescale Everything! version v2.4.6.8.

**Comment by StarCrusher96** [comment]
Hi, when did you update? 
I updated yesterday the _core to fix those warnings / errors.

**Comment by linuxgurugamer** [comment]
> I'm using the [1.2 tag](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/releases/tag/1.2). I've just re-downloaded it and I still have the error.
> 
> Where can I find your updated core? Is it on a separate repository? If you can send me a link to download it I can test it out here.

From the README:

PREVIOUS VERSION:   (!!never install an update over previous version!!)

**Comment by StarCrusher96** [comment]
They should be gone, if you redownload _Core (removed the old one ofc) and the error persists. Plz notify me and add a screen.

**Comment by RenatoUtsch** [comment]
Hey, I delete the previous version and install the new one from a fresh setup, I didn't install it over the previous version.

I don't think the files with errors are gone from the 1.2 tag. The tag was made on January 2nd 2022, and if I download GU_Core.zip from the [1.2 tag](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/releases/tag/1.2) link I can still find the two files with errors:

![Screenshot from 2022-02-15 11-23-59](https://user-images.githubusercontent.com/836333/154081749-afaecd81-f4d8-4156-92e8-3db38e21fcee.png)

I also deleted my previous installation (completely removed the GU-related folders) and installed GU again and the errors persist with the 1.2 tag. From what I understood in your previous comment you updated _core on February 10th:

> Hi, when did you update? I updated yesterday the _core to fix those warnings / errors.

How do I find this updated version? Is there a place in the main branch that stores the updated GU_Core.zip asset? I couldn't find it apart from the page listing the 1.2 release tag.

**Comment by RenatoUtsch** [comment]
Ok, I've just deleted everything and done a fresh install. I can confirm from the download on the releases page that the 2.5x.cfg and 10x.cfg files inside the zip files were modified on February 10th:
![Inked7zFM_2022-02-16_20-22-42_LI](https://user-images.githubusercontent.com/836333/154374631-a8054ab1-d66e-45c5-af2b-c37b75bf4fb8.jpg)

However, the error continues to happen:
![KSP_x64_2022-02-16_20-28-07](https://user-images.githubusercontent.com/836333/154374893-3d483d53-9f30-4e2c-bba1-447d3f8c2c06.jpg)

Here is the output from a fresh KSP.log, still the same error:
```
[ERR 20:27:30.125] Error - node name does not have balanced brackets (or a space - if so replace with ?):
GU/Configs/GU_Patches/Rescale_Sigma/10x/@Kopernicus:HAS[@GU_GENERAL_Settings]:HAS[#Scale[10]]]:BEFORE[SigDim]
[ERR 20:27:30.125] Error - node name does not have balanced brackets (or a space - if so replace with ?):
GU/Configs/GU_Patches/Rescale_Sigma/2.5x/@Kopernicus:HAS[@GU_GENERAL_Settings]:HAS[#Scale[2.5]]]:BEFORE[SigDim]
[WRN 20:27:30.125] unrecognized trailer: ',*' on: GU/Configs/GU_Patches/Rescale_Sigma/2.5x/@EVE_CLOUDS[*]:LAST[GU]:HAS[@GU_GENERAL_Settings:HAS[#Scale[2.5]]],*`
...
[LOG 20:27:41.982] Done patching
[WRN 20:27:41.983] 1 warning related to GameData/GU/Configs/GU_Patches/Rescale_Sigma/2.5x.cfg
[WRN 20:27:41.983] Errors in patch prevents the creation of the cache
[LOG 20:27:42.095] ModuleManager: 6850 patches applied, found <color=yellow>1 warning</color>, found <color=orange>2 errors</color>
1 error related to GameData/GU/Configs/GU_Patches/Rescale_Sigma/10x.cfg
1 error related to GameData/GU/Configs/GU_Patches/Rescale_Sigma/2.5x.cfg

[LOG 20:27:42.095] Ran in 13.423s
[LOG 20:27:42.101] Done!
```

Please let me know how I can help you debug this issue further.

**Comment by RenatoUtsch** [comment]
They are not gamebreaking, so I'm playing even though these errors are there.

I have downloaded a fresh copy of _Core from the GU 1.2 page and installed everything from scratch 3 times this past week: on Feb 10th, on Feb 11th and on Feb 16th and I still continue having the error. My friend also installed GU 1.2 on Feb 15th and he is also having the error. Maybe these files were not updated when you launched the latest version of _Core? Could something else be affecting it as well?

**Comment by StarCrusher96** [comment]
Can you post logs? 
The updated files are in the current _core dl. No reports have been made about them since i updated them. So I'm curious why you still have it.

**Comment by linuxgurugamer** [comment]
Here, this page will explain it:  http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

**Comment by gillmi** [comment]
I'm getting a similar error with rescale_sigma, but for me, Kopernicus won't even load the planets. Here's a link to my logs: https://drive.google.com/drive/folders/1uN_MQVfIyi7o3SAhZFYtasYx31uJhLmJ?usp=sharing

**Comment by RenatoUtsch** [comment]
If you download the latest _core (I've downloaded it _10 minutes ago_) and open it on a text editor you'll see that it is still clearly broken - the 2.5x.cfg and 10x.cfg files have obvious syntax errors:

![gvim_2022-02-19_11-01-35](https://user-images.githubusercontent.com/836333/154804181-c729977a-5edd-4698-aea7-52a9638fcab5.png)

I've gone ahead and fixed these issues and ModuleManager stopped complaining. Here are the two fixed files:

[Rescale_Sigma.zip](https://github.com/StarCrusher96/Galaxies-Unbound-A-Stellar-Odyssey/files/8102312/Rescale_Sigma.zip)

**Comment by RenatoUtsch** [comment]
Maybe what is happening is that these two files were not updated for some weird github reason when the _core download was last updated? As far as I know tags in git are not supposed to change after they're created.

I suggest making a new tag, i.e. a 1.2.1 release with the updated download files. This will also make people notice that there were updates since 1.2 was released.

**Comment by gillmi** [comment]
> I'm getting a similar error with rescale_sigma, but for me, Kopernicus won't even load the planets. Here's a link to my logs: https://drive.google.com/drive/folders/1uN_MQVfIyi7o3SAhZFYtasYx31uJhLmJ?usp=sharing

Forget this, I accidentally had StellarAdventures inside the folder when updating.

**Comment by RenatoUtsch** [comment]
I've just downloaded the new 1.2.1 patch and can confirm the issue is fixed on the latest _Core download now. Thank you so much for your help!
